### ISSUE TITLE
jruby MessagePack::Unpacker is loading all data from stream

### ISSUE THREAD

**Issue by kirillrdy** [msgpack/msgpack-ruby#138] opened 2017-07-02 22:11 UTC
It looks like mri version of unpacker does buffered reads from the stream when given an io, but jruby version is loading all data from stream into memory.
Example code
```ruby
file = File.new("some_large_file", "rb")
MessagePack::Unpacker.new(file) # in jruby reads all file here
```
I hope this finding at least helps someone

**Comment by chrisseaton** [comment] 2022-07-19 19:10
Useful information, but closing as not a bug unless someone has an issue with the behaviour.

**Closed by chrisseaton** 2022-07-19 19:10 UTC
